[package]
name = "dotnet_host"
version = "0.1.0"
authors = ["Marvin Countryman <me@maar.vin>"]
edition = "2018"

[[bench]]
name = "prelim"
path = "benches/prelim.rs"
harness = false

[dependencies]
dotnet_hostfxr = "^0.1"

[dev-dependencies]
criterion = "*"
